robotiq_gripper_controller:
  ros__parameters:
    action_monitor_rate: 20.0 # Hz
    joint: $(var tf_prefix)robotiq_hande_left_finger_joint
    max_effort: 10.0 # N
    goal_tolerance: 0.01 # m
    allow_stalling: false
    stall_velocity_threshold: 0.001 #m/s
    stall_timeout: 1.0 # s
    state_interfaces:
      - position